language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t iamaborg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true iamaborg/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-781751860340"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
