sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t iamaborg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true iamaborg/docker-react npm run test

